### ISSUE TITLE
Error when trying to enable the module

### ISSUE THREAD

**Issue by a12l** [foo-dogsquared/nix-overlay-guix#5]
I get this error when I try to enable this overlay on my NixOS config. I'm on `nixos-unstable`. Not sure what info you need to debug this error.

[guix-error.txt](https://github.com/foo-dogsquared/nix-overlay-guix/files/9946752/guix-error.txt)

**Comment by foo-dogsquared** [comment]
The build logs you gave is similar that someone gave from an issue which [I gave a solution](https://github.com/foo-dogsquared/nix-overlay-guix/issues/3#issuecomment-1303512770).

To reiterate, the problem is the version of libssh in the unstable branch is not compatible with guile-ssh which I assume you're using the overlay from this flake. It only works on 22.05 stable branch for now. As a workaround, you'll have to remove the overlay, make sure the Guix overlay flake follows nixpkgs 22.05 branch, and point `services.guix.package` to the package that came with this flake (for example, `services.guix.package = inputs.guix-overlay.packages.x86_64-linux.guix`).

**Comment by a12l** [comment]
Thanks! That solved it for me.
